name: Release project to packages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifactId: ${{ steps.artifact-id.outputs.artifactId}}
      artifactVersion: ${{ steps.artifact-version.outputs.artifactVersion}}
    steps:
      - uses: actions/checkout@v3
      - id: java-setup
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'zulu'
          cache: 'maven'
      - id: build
        name: Execute Maven Build
        run: './mvnw clean verify'
        env:
          SPRING_PROFILES_ACTIVE: 'test'
      - id: release-version
        name: Get Release Version
        run: |
          ./mvnw release: prepare -DdryRun=true
      - id: artifact-id
        name: Get Artifact Id
        run: |
          echo "::set-output name=artifactId::$(./mvnw -f pom.xml.tag help:evaluate -Dexpression=project.artifactId -q -DforceStdout)"
      - id: artifact-version
        name: Get Artifact New Version
        run: |
          echo "::set-output name=artifactVersion::$(./mvnw -f pom.xml.tag help:evaluate -Dexpression=project.version -q -DforceStdout)"
      - id: cleanup
        name: Reverse release dry run
        run: ./mvnw release:clean

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - id: java-setup
        name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'zulu'
          cache: maven
      - id: git_config
        name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - id: release
        name: Release to packages
        run: |
          ./mvnw release:prepare release:perform -B -s .maven_settings.xml
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          SPRING_PROFILES_ACTIVE: "test"

  containerize:
    runs-on: ubuntu-latest
    needs: [build,release]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/tags/${{needs.build.outputs.artifactVersion}}
      - id: java-setup
        name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'zulu'
          cache: maven
      - id: docker_login
        name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - id: build_image
        name: Build Docker image - no tests
        run: ./mvnw clean verify -DskipTests=true jib:dockerBuild
      - id: docker_push
        name: Push to DockerHub
        run: docker push anthonyikeda/${{needs.build.outputs.artifactId}}:${{needs.build.outputs.artifactVersion}}
